EasyBooksWebApp/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EasyBooksWebApp.Data;
using EasyBooksWebApp.Models;

namespace EasyBooksWebApp.Controllers
{
    public class BillsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BillsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Bills
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await GetUserQueryable().
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.Bills)
                    .SingleOrDefaultAsync();

                var bills = user.Suppliers.SelectMany(c => c.Bills).ToList();
                return View(bills);
            }
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        // GET: Bills/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var user = await GetUserQueryable().
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.Bills).
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.State)
                    .SingleOrDefaultAsync();

                var bill = user.Suppliers.SelectMany(c => c.Bills).SingleOrDefault(b => b.BillID == id);
                if (bill == null)
                {
                    return NotFound();
                }

                return View(bill);
            }
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        // GET: Bills/Create
        public async Task<IActionResult> Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await GetUserQueryable().
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.State)
                    .SingleOrDefaultAsync();

                var supplierList = user.Suppliers.Select(s => new { SupplierID = s.SupplierID, Description = s.FirstMidName + " " + s.LastName + ", " + s.State.Name });
                ViewData["SupplierID"] = new SelectList(supplierList, "SupplierID", "Description");
                return View();
            }
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        // POST: Bills/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BillID,SupplierID,BillNo,BillDate,DueDate,Memo,TotalAmount")] Bill bill)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(bill);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

                var user = await GetUserQueryable().
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.State)
                    .SingleOrDefaultAsync();

                var supplierList = user.Suppliers.Select(s => new { SupplierID = s.SupplierID, Description = s.FirstMidName + " " + s.LastName + ", " + s.State.Name });
                ViewData["SupplierID"] = new SelectList(supplierList, "SupplierID", "Description", bill.SupplierID);
                return View(bill);
            }
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        // GET: Bills/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var user = await GetUserQueryable().
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.Bills).
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.State)
                    .SingleOrDefaultAsync();

                var bill = user.Suppliers.SelectMany(c => c.Bills).SingleOrDefault(b => b.BillID == id);
                if (bill == null)
                {
                    return NotFound();
                }
                var supplierList = user.Suppliers.Select(s => new { SupplierID = s.SupplierID, Description = s.FirstMidName + " " + s.LastName + ", " + s.State.Name });
                ViewData["SupplierID"] = new SelectList(supplierList, "SupplierID", "Description", bill.SupplierID);
                return View(bill);
            }
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        // POST: Bills/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("BillID,SupplierID,BillNo,BillDate,DueDate,Memo,TotalAmount")] Bill bill)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id != bill.BillID)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(bill);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!BillExists(bill.BillID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }

                var user = await GetUserQueryable().
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.State)
                    .SingleOrDefaultAsync();

                var supplierList = user.Suppliers.Select(s => new { SupplierID = s.SupplierID, Description = s.FirstMidName + " " + s.LastName + ", " + s.State.Name });
                ViewData["SupplierID"] = new SelectList(supplierList, "SupplierID", "Description", bill.SupplierID);
                return View(bill);
            }
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        // GET: Bills/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var user = await GetUserQueryable().
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.Bills).
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.State)
                    .SingleOrDefaultAsync();

                var bill = user.Suppliers.SelectMany(c => c.Bills).SingleOrDefault(b => b.BillID == id);
                if (bill == null)
                {
                    return NotFound();
                }

                return View(bill);
            }
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await GetUserQueryable().
                    Include(u => u.Suppliers).
                        ThenInclude(s => s.Bills)
                    .SingleOrDefaultAsync();

                var bill = user.Suppliers.SelectMany(c => c.Bills).SingleOrDefault(b => b.BillID == id);
                if (bill == null)
                {
                    return NotFound();
                }

                _context.Bill.Remove(bill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(AccountController.Login), "Account");
        }

        #region Helpers

        private bool BillExists(long id)
        {
            return _context.Bill.Any(e => e.BillID == id);
        }

        private IQueryable<ApplicationUser> GetUserQueryable()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return _context.Users.Where(u => u.UserName.Equals(User.Identity.Name));
            }
            return null;
        }

        #endregion
    }
}

EasyBooksWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EasyBooks</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EasyBooks</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Customer <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Customers" asp-action="Index">Customers</a></li>
                                <li><a asp-area="" asp-controller="Invoices" asp-action="Index">Invoices</a></li>
                                <li><a asp-area="" asp-controller="ReceivePayments" asp-action="Index">Receive Payments</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Supplier <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a></li>
                                <li><a asp-area="" asp-controller="Bills" asp-action="Index">Bills</a></li>
                                <li><a asp-area="" asp-controller="BillPayments" asp-action="Index">Bill Payments</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year.ToString() - EasyBooks</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>